parameters: 
- name: directoryPath
  type: string

steps: 
- download: none
- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'current'
    artifactName: 'Drop'
    itemPattern: |
      **
      *
    targetPath: '${{ parameters.directoryPath }}/'
