steps: 
- download: none
- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'current'
    artifactName: 'Drop'
    itemPattern: |
      **
      *
    targetPath: '$(Agent.BuildDirectory)/Drop/'