steps: 
- task: PowerShell@2
  inputs:
    filePath: '$(DROP_PATH)/Scripts/getLatestVersion.ps1'
    arguments: '-propertiesPath "$(PROPERTIES_PATH)"'

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'ramsessanchez'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'userSpecifiedTag'
    tag: '$(VERSION_STRING)-$(Build.BuildNumber)'
    assets: |
      !**/**
      $(Build.ArtifactStagingDirectory)/*
    isPreRelease: true
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased' 