#Copyright (c) Microsoft Corporation. All rights reserved.
#Licensed under the MIT License.
#Building and packaging the artifacts of the Java-SDK-Beta libraries using the build.gradle file.
#Ready the package for deployment and release. 

trigger:
  branches:
    include: 
      - dev
  paths:
    include:
      - src/*
    exclude:
      - .gradle/wrapper
      - .gitignore
      - CONTRIBUTING.md
      - LICENSE
      - THIRD PARTY NOTICES
      - gradle.properties
      - gradlew
      - gradlew.bat
      - readme.md
      - settings.gradle
      - Scripts/*
  
pr: 
- dev

pool: 
  vmImage: windows-latest

stages: 
- stage: Build 
  jobs: 
  - job: 
    steps: 
    - template: templates/build/checkout-and-credscan.yml
    - template: templates/install-java.yml
    - template: templates/secure-files.yml
      parameters: 
        stageID: 'build'
    - template: templates/build/pipeline-build.yml
    - template: templates/build/publish-artifacts.yml

- stage: Maven_Preview_And_Github_Release
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/dev'))
  jobs: 
  - deployment: Maven_Preview
    environment: 'MSGraph SDK Development - Java'
    pool: 
      vmImage: windows-latest
    strategy: 
     runOnce: 
      deploy: 
        steps: 
        - template: templates/download-artifacts.yml
        - template: templates/install-java.yml
        - template: templates/secure-files.yml 
        - template: templates/copy-and-build.yml

  - deployment: Github_Release
    dependsOn: Maven_Preview
    environment: 'MsGraph SDK Development - Java'
    pool: 
      vmImage: windows-latest
    strategy:
     runOnce:
      deploy:   
        steps: 
        - template: templates/download-artifacts.yml
        - template: templates/version-and-release.yml
          parameters:
            gitConnection: 'microsoftgraphrelease'
