name: "Checks the SDK only using APIs from the targeted API level"

on: 
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
      - feature/v3

jobs:
  lint-api-level:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Add execution right to the script
        run: chmod +x gradlew
        working-directory: ./android
      - name: Build SDK with Android project configuration
        id: lint
        run: ./gradlew --no-daemon build
        working-directory: ./android
      - name: Upload linting results
        if: failure() && steps.lint.outcome == 'failure'
        uses: actions/upload-artifact@v2
        with:
          name: lint-report
          path: ./android/build/reports
