# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build and Preview 

on:
  push:
    branches: [ dev ]
    paths:
     - 'src/**'
     - '.github/**'
     - '!.gradle/wrapper'
     - '!.gitignore'
     - '!LICENSE'
     - '!THIRD PARTY NOTICES'
     - '!*.md'
     - '*.gradle'
  workflow_dispatch: 
  
env: 
  PREVIEW_TASK: publishSnapshotPublicationToSonatypeSnapshotRepository

jobs:
  maven_Preview:
    environment: 
      name: maven_central_snapshot
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Easy detect-secrets
        uses: RobertFischer/detect-secrets-action@v2.0.0
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
          cache: gradle
      - run: .\Scripts\decodeAndWrite.ps1 -encodedValue $env:ENCODED_VALUE -outputPath $env:OUTPUT_PATH  
        shell: pwsh
        env:  
          ENCODED_VALUE: ${{ secrets.LOCAL_PROPERTIES }}
          OUTPUT_PATH: .\local.properties 
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Publish
        run: ./gradlew $PREVIEW_TASK
  
  github_Release: 
    needs: maven_Preview
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v2.0.10
        with: 
          name: drop
          path: drop        
      - name: GitHub Releases
        uses: fnkr/github-action-ghr@v1.3
        env:
          GHR_PATH: current/working/directory/drop/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
